apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lSQUtZYVF2TldrcVhqMkRkN2ZnaXpLdUF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNE16RXhPRFUyTVRKYUZ3MHpNVEE0TXpBeApPRFUyTVRKYU1CVXhFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUMyaTJ2U0xBQzJqMGp5MVlLd3N6NHBONFJ6bGJWRnZUWjk3MFZxcHpieWt3SjkKZW9XRGozOThjRlQ0aHo5UjhtNnQwRnE2dzc5d0l3dno5bDlVRHB4QWVZTWpuNmRwMlhPMDJ2THJpY1JKOFZmcgpFZ1BpYnpEaEg3blY5VjNIWEcvZ2J6M1RRUEVHeWd5MnhNMjdrZW83a0dSbU5QK2VpdTRHcFpneCtGQXl1aVBhCkpsaFRndm43TEZWdWJXVnhDRzl2RUlkTVFkeStSMTlmVFg1K21ORThibDZidGY2M0xnOUJjMjNsZERiZE52VTcKZ0ZyczJKNERPZU1oc3IySkxqZmVhUHdUN3pxUWhBUmlSQVZFYy9qWkxXb3B4SFJLSDVOOXlHT0ZTSlVyZ3JXdgpPeXJYUURIL0NkYjllbzR6eDhBWVhBb2xsQnNTZWRiUllHRDBmbksxQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCCi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSb1ZicW43U2p3TWhkTGdEM3EKUWRxVlN4YnMwakFWQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUNENDBwZXIrREZ6YXZkcTZDekdDWXorSzRrczRBNytxTXBEZmZPTWFMRjBjdlJnSjVHbmdQaGZZNTFyOWVXCjNhT3Q1Y1lPYXVhbFcvS1hNN2UxYUdiNHZMWm51czdPNVIyOFNVajY3OHVNOTNSZXRaLzZOemVRRmZQUmwrai8KcG9oUTZyMEVPdVRNZUdrc0VKMFRoa0YyWm5zYlZ5aXBZeWRINUNsa0xiOHNBWkdINU1pVFk3WStMR1BlQi9wcQp2NkNmRjJ4SVUxZEx3NU5uYy9tUGlYbUR6bTh3MG1oT0RLc3U4U0FPVlA5VFlxZStsSEw0YnAwdEo3OVlYd0FRCkRMcGJaMm1NUUNQbU1sSENEWmpONjdSaldFUmFkQk9idytJRGdwZWZVblZacHFXN2MzMi9qcHcwZ0UrN0RCQ2kKM0dOY3VkNC9Ec3FvRzgwUjRZN3dvK1h3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://D792E142504B0645CFBD1A2622305D98.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:729468325479:cluster/myapp-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:729468325479:cluster/myapp-eks-cluster
    user: arn:aws:eks:us-east-1:729468325479:cluster/myapp-eks-cluster
  name: arn:aws:eks:us-east-1:729468325479:cluster/myapp-eks-cluster
current-context: arn:aws:eks:us-east-1:729468325479:cluster/myapp-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:729468325479:cluster/myapp-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - myapp-eks-cluster
      - --output
      - json
      command: aws
